[project]
name = "stdlibx-cancel"
version = "0.1.0"
description = "stdlibx-cancel"
authors = [
    { name = "Lucino772" }
]
requires-python = ">=3.9.25"
dependencies = [
    "typing_extensions>=4.10.0,<5"
]

[tool.uv.build-backend]
module-name = "stdlibx.cancel"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
