[project]
name = "stdlibx-compose"
version = "0.1.0"
description = "stdlibx-compose"
license = "MIT"
license-files = ["LICEN[CS]E*"]
readme = "README.md"
authors = [
    { name = "Lucino772" }
]
requires-python = ">=3.9"
dependencies = [
    "typing_extensions>=4.10.0,<5"
]

[project.urls]
Documentation = "http://stdlibx.lucapalmi.com/"
Repository = "https://github.com/Lucino772/stdlibx"

[tool.uv.build-backend]
module-name = "stdlibx.compose"

[build-system]
requires = ["uv_build>=0.9.28,<0.10.0"]
build-backend = "uv_build"
